homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude:  !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

zone:
  name: Work
  latitude: !secret work_lat
  longitude: !secret work_lon
  radius: 250
  icon: mdi:work

zone 2:
  name: !secret zone2_name
  latitude: !secret com_lat
  longitude: !secret com_long
  radius: 100
  icon: !secret zone2_icon

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  
# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor: !include sensors.yaml  

# Text to speech
tts:
  platform: google

group: !include groups.yaml

media_player:
   - platform: apple_tv
     host: !secret apple_tv_host
     login_id: !secret apple_tv_login
     name: Living Room ATV
device_tracker:
   - platform: unifi
     username: !secret unifi_username
     password: !secret unifi_password
     host: !secret unifi_host
     port: !secret unifi_port
     verify_ssl: false
     
light:
   - platform: hue
     host: !secret hue_host

switch: !include switches.yaml

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password
  
zwave:
  usb_path: !secret zwave_path

notify:
   - name: pushbullet
     platform: pushbullet
     api_key: !secret pushbullet_api
   - name: slack
     platform: slack
     api_key: !secret slack_api_key
     default_channel: '#general'
     
ios:

automation: !include automation.yaml

ifttt:
  key: !secret ifttt_key

#hdmi_cec:
#  devices:
#    TV: 0.0.0.0
#    Apple TV: 1.0.0.0
#    hassbian: 2.0.0.0
